---
- name: installing tomcat 10 on ubuntu
  hosts: all
  become: yes
  tasks:
    - name: update the packages and install java 
      ansible.builtin.apt:
        name: "{{ java_package }}"
        state: present
        update_cache: true
    -  
  
      




        