---
- name: install tomcat 10 on ubuntu
  hosts: ubuntu
  become: yes
  tasks:
    - name: update packages and install java 
      ansible.builtin.apt:
        name: "{{ java_package }}"
        update_cache: yes
        state: present
    - name: create a group tomcat
      ansible.builtin.group:
        name: "{{ group_name }}"
        state: present
    - name: create a system user tomcat
      ansible.builtin.user:
        name: "{{ user_name }}"
        create_home: true
        group: "{{ group_name }}"
        home: "{{ home_dir }}"
        shell: "{{ default_shell }}"
        state: present
    - name: download and extract the file
      ansible.builtin.unarchive:
        src: "https://dlcdn.apache.org/tomcat/tomcat-10/v{{ tomcat_version }}/bin/apache-tomcat-{{ tomcat_version }}.tar.gz"     
        dest: "{{ home_dir }}"
        remote_src: yes  
    - name: create a symbolic link
      ansible.builtin.file:
        src: "{{ home_dir }}/apache-tomcat-{{ tomcat_version }}"
        dest: "{{ home_dir }}/latest"
        owner: "{{ user_name }}"
        group: "{{ group_name }}"
        state: link
    - name: changing ownership to the user
      ansible.builtin.file:
        path: "{{ home_dir }}"
        state: directory
        recurse: yes
        owner: "{{ user_name }}"
        group: "{{ group_name }}"   
    - name: giving  shell permissions
      ansible.builtin.shell:
        cmd: 'chmod +x /opt/tomcat/latest/bin/*.sh'
        executable: /bin/bash
    - name: adding tomcat.service file
      ansible.builtin.copy:
        src: tomcat.service
        dest: /etc/systemd/system/tomcat.service
    - name: restart tomcat
      ansible.builtin.systemd:
        name: tomcat.service
        enabled: yes
        state: started 
    - name: configuring tomcat web management
      ansible.builtin.copy:
        src: tomcat-users.xml
        dest: "{{ home_dir }}/latest/conf/tomcat-users.xml"
    - name: configuring manager app
      ansible.builtin.copy:  
        src: manager_context.xml
        dest: "{{ home_dir }}/latest/webapps/manager/META-INF/context.xml"      
    - name: configuring host manager app
      ansible.builtin.copy:  
        src: hostmanager_context.xml
        dest: "{{ home_dir }}/latest/webapps/host-manager/META-INF/context.xml"      
    - name: restart tomcat
      ansible.builtin.systemd:
        name: tomcat.service
        state: restarted             
           


      